import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { validateSession } from "@/lib/auth";
import { cn } from "@/lib/utils";
import Providers from "@/providers/providers";
import { SessionProvider } from "@/providers/session-provider";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sessionData = await validateSession();

  return (
    <html lang="en" className="dark">
      <body
        className={cn(
          "min-h-screen font-sans text-text antialiased",
          inter.className,
        )}
      >
        <SessionProvider value={sessionData}>
          <Providers>{children}</Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
